routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::resource('photo','PhotosController')->except(['index','show',]);
Auth::routes();
Route::get('/user_cabinet','UserController@index')->name('user_cabinet');
Route::post('photo/{id}/like','LikesController@addOrDeleteLike')->name('like-action');
Route::post('/user/{id}/subscribeOf','UserController@subscribe')->name('subscribe');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/add/comment/photo/{id}','CommentController@addComment')->name('add-comment');
Route::delete('/destroy/comment/{id}','CommentController@destroy')->name('destroy-comment');

app/User.php
<?php

namespace App;

use Orchid\Platform\Models\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'last_login',
        'permissions',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'permissions',
        'uses_two_factor_auth',
        'two_factor_secret_code',
        'two_factor_recovery_code',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'permissions'          => 'array',
        'email_verified_at'    => 'datetime',
        'last_login'           => 'datetime',
        'uses_two_factor_auth' => 'boolean',
    ];

    /**
     * The attributes for which you can use filters in url.
     *
     * @var array
     */
    protected $allowedFilters = [
        'id',
        'name',
        'email',
        'permissions',
    ];

    /**
     * The attributes for which can use sort in url.
     *
     * @var array
     */
    protected $allowedSorts = [
        'id',
        'name',
        'email',
        'last_login',
        'updated_at',
        'created_at',
    ];
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function subscribersMine()
    {
        return $this->belongsToMany(User::class,'subscribers','user_id','follower_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function subscribersOf()
    {
        return $this->belongsToMany(User::class,'subscribers','follower_id','user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $user = $request->user();
        return view('user.index',compact('user'));
    }


    public function subscribe(Request $request,$id)
    {
        $auth_user = $request->user();
        $fallow_user = User::findOrFail($id);
        if ($auth_user->subscribersOf->contains($fallow_user->id))
        {
            return back()->with('status', "You are already subscribed {$fallow_user->name}");
        }else
            {
                $auth_user->subscribersOf()->attach($fallow_user->id);
                return back()->with('status', "You subscribed {$fallow_user->name}");
            }
    }
}

resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
    <h1 class="main-title">{{$user->name}}</h1>
    <button type="button" class="btn btn-primary main-title"><a class="links" href="{{route('photo.create')}}">Add Photo</a></button>

    <div class="row">
        @foreach($user->photos as $photo)
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                @if($photo->photo !== 'noPhoto.jpg')
                    <img class="card-img-top" src="{{asset('/storage/' .
                        $photo->photo)}}" alt="photo">
                @else
                    <img src="{{asset('noPhoto.jpg')}}" class="card-img-top" alt="No photo">
                @endif
                        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#comment{{$photo->id}}" aria-expanded="false" aria-controls="collapseExample">
                            Comments
                        </button>
                        @foreach($photo->comments->where('active',true) as $comment)
                            <div class="collapse comment" id="comment{{$photo->id}}">
                                <div class="card card-body">
                                    <h4>{{$comment->user->name}}</h4>
                                    {{$comment->body}}
                                </div>
                                @can('destroy',$comment)
                                    <form  method="post"  action="{{ route('destroy-comment',$comment->id) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button class="like btn-danger" type="submit">Delete</button>
                                    </form>
                                @endcan
                            </div>
                        @endforeach
                <p class="photo-title">{{$photo->title}}</p>
                <div class="card-body">
                    <p class="card-text">{{$photo->description}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <form method="post" action="{{route('photo.destroy',['photo' => $photo])}}">
                                @method('delete')
                                @csrf
                                <button type="submit" class="btn btn-sm btn-outline-secondary">delete</button>
                            </form>
                            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{route('photo.edit',['photo' => $photo])}}">edit</a></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            @endforeach
    </div>
    @endsection