routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::resource('photo','PhotosController')->except(['index','show',]);
Auth::routes();
Route::get('/user_cabinet','UserController@index')->name('user_cabinet');
Route::post('photo/{id}/like','LikesController@addOrDeleteLike')->name('like-action');
Route::post('/user/{id}/subscribeOf','UserController@subscribe')->name('subscribe');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/add/comment/photo/{id}','CommentController@addComment')->name('add-comment');
Route::delete('/destroy/comment/{id}','CommentController@destroy')->name('destroy-comment');

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
        'user_id',
        'title',
        'photo',
        'description'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PhotoRequest;
use App\Photo;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PhotosController extends Controller
{
    /**
     * PhotosController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('photo.create');
    }


    /**
     * @param PhotoRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(PhotoRequest $request)
    {
        $user = $request->user();
        $photo = new Photo();
        $photo->user_id = $user->id;
        $photo->description = $request->input('description');
        $photo->title = $request->input('title');
        $file = $request->file('photo');
        if (!is_null($file)) {
            $path = $file->store('photo', 'public');
            $photo['photo'] = $path;
        }
        $photo->save();
        return redirect(route('user_cabinet'))->with('status', "Photo {$photo->title} success added!");
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit($id)
    {
        $photo = Photo::findOrFail($id);
        $this->authorize('edit',$photo);
        return view('photo.edit',compact('photo'));
    }


    /**
     * @param PhotoRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(PhotoRequest $request, $id)
    {
        $photo = Photo::findOrFail($id);
        $data = $request->all();
        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $path = $file->store('photo', 'public');
            $data['photo'] = $path;
        }
        $photo->update($data);
        return redirect(route('user_cabinet'))->with('status', "Photo {$photo->title} success updated!");
    }


    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $photo = Photo::findOrFail($id);
        $this->authorize('delete',$photo);
        $photo->delete();
        return redirect(route('user_cabinet'))->with('status', "Photo {$photo->title} success updated!");
    }
}

resources/views/photo/create.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="margin-top: 25px;">Add photo</h1>
    <form method="post" action="{{route('photo.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="title">Photo title</label>
            <input type="text"  class="form-control @error('title') is-invalid @enderror" id="title" name="title">
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <label for="description">Photo description</label>
        <div class="form-group">
            <textarea  name="description" id="description" cols="135" rows="5"></textarea>
        </div>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('photo') is-invalid @enderror" id="customFile" name="photo">
                @error('photo')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <label class="custom-file-label" for="customFile">Choose picture</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Add photo</button>
    </form>
    @endsection

resources/views/photo/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="margin-top: 25px;">Add photo</h1>
    <form method="post" action="{{route('photo.update',$photo)}}" enctype="multipart/form-data">
        @method('put')
        @csrf
        <div class="form-group">
            <label for="title">Photo title</label>
            <input type="text"  value="{{$photo->title}}" class="form-control @error('title') is-invalid @enderror" id="title" name="title">
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <label for="description">Photo description</label>
        <div class="form-group">
            <textarea  name="description" id="description" cols="135" rows="5">{{$photo->description}}</textarea>
        </div>
        <figure class="figure">
        @if($photo->photo !== 'noPhoto.jpg')
            <img class="figure-img img-fluid rounded" src="{{asset('/storage/' .
                        $photo->photo)}}" alt="photo">
        @else
            <img src="{{asset('noPhoto.jpg')}}" class="figure-img img-fluid rounded" alt="No photo">
        @endif
        </figure>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('photo') is-invalid @enderror" id="customFile" name="photo">
                @error('photo')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <label class="custom-file-label" for="customFile">Choose picture</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Update photo</button>
    </form>
@endsection